AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for command ledger and object metadata.

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  Version:
    Type: String
  CommandLedgerBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
  ObjectMetadataBillingMode:
    Type: String
    Default: PAY_PER_REQUEST

Resources:
  CommandLedgerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-command-ledger-${Version}"
      BillingMode: !Ref CommandLedgerBillingMode
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  ObjectMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-object-metadata-${Version}"
      BillingMode: !Ref ObjectMetadataBillingMode
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  CommandLedgerTableArn:
    Value: !GetAtt CommandLedgerTable.Arn
  CommandLedgerTableName:
    Value: !Ref CommandLedgerTable
  ObjectMetadataTableArn:
    Value: !GetAtt ObjectMetadataTable.Arn
  ObjectMetadataTableName:
    Value: !Ref ObjectMetadataTable
