AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with versioning enabled and EventBridge notifications.

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  Version:
    Type: String

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${Environment}-source-${Version}"
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucket
  SourceBucketArn:
    Value: !GetAtt SourceBucket.Arn
